import 'dart:math';

/// Injectable source of entity identifiers.
///
/// Sits beside `Clock` and for the same reason: an id generated by calling a
/// global is untestable, and every test that compares a stored entity then has
/// to work around a value it cannot predict.
abstract interface class IdGenerator {
  /// Returns a new identifier.
  String next();
}

/// Production generator.
///
/// Ids are `<timestamp>-<random>`, both base-36. The timestamp prefix makes ids
/// sort roughly by creation, which keeps index locality reasonable and makes a
/// database dump readable; the random suffix supplies the uniqueness. Both
/// halves matter — a timestamp alone collides when two records are created in
/// the same millisecond.
final class SystemIdGenerator implements IdGenerator {
  /// Creates a generator. [random] and [now] are injectable for tests that
  /// need to force a collision or a fixed prefix.
  SystemIdGenerator({Random? random, DateTime Function()? now})
    : _random = random ?? Random.secure(),
      _now = now ?? (() => DateTime.now().toUtc());

  final Random _random;
  final DateTime Function() _now;

  /// Number of base-36 characters of randomness.
  static const int randomLength = 10;

  /// Width the timestamp is padded to, so ids sort lexicographically for any
  /// date this app will see.
  static const int timestampWidth = 9;

  @override
  String next() {
    final stamp = _now().millisecondsSinceEpoch
        .toRadixString(36)
        .padLeft(timestampWidth, '0');
    final buffer = StringBuffer();
    for (var i = 0; i < randomLength; i++) {
      buffer.write(_random.nextInt(36).toRadixString(36));
    }
    return '$stamp-$buffer';
  }
}

/// Deterministic generator for tests.
final class FixedIdGenerator implements IdGenerator {
  /// Emits `<prefix>-1`, `<prefix>-2`, … in order.
  FixedIdGenerator({this.prefix = 'id'});

  /// Prefix for every generated id.
  final String prefix;

  int _counter = 0;

  /// How many ids have been handed out.
  int get count => _counter;

  @override
  String next() {
    _counter++;
    return '$prefix-$_counter';
  }
}
